# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .lxc_container import *
from .lxc_disk import *
from .provider import *
from .qemu_vm import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_proxmox.config as config
else:
    config = _utilities.lazy_import('pulumi_proxmox.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "proxmox",
  "mod": "index/lXCContainer",
  "fqn": "pulumi_proxmox",
  "classes": {
   "proxmox:index/lXCContainer:LXCContainer": "LXCContainer"
  }
 },
 {
  "pkg": "proxmox",
  "mod": "index/lXCDisk",
  "fqn": "pulumi_proxmox",
  "classes": {
   "proxmox:index/lXCDisk:LXCDisk": "LXCDisk"
  }
 },
 {
  "pkg": "proxmox",
  "mod": "index/qemuVM",
  "fqn": "pulumi_proxmox",
  "classes": {
   "proxmox:index/qemuVM:QemuVM": "QemuVM"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "proxmox",
  "token": "pulumi:providers:proxmox",
  "fqn": "pulumi_proxmox",
  "class": "Provider"
 }
]
"""
)
